# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoWindow(object):
    def setupUi(self, InfoWindow):
        InfoWindow.setObjectName("InfoWindow")
        InfoWindow.setWindowModality(QtCore.Qt.WindowModal)
        InfoWindow.resize(396, 342)
        font = QtGui.QFont()
        font.setPointSize(12)
        InfoWindow.setFont(font)
        InfoWindow.setStyleSheet("background-color: rgb(224, 255, 207);")
        self.centralwidget = QtWidgets.QWidget(InfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header_label = QtWidgets.QLabel(self.centralwidget)
        self.header_label.setGeometry(QtCore.QRect(20, 20, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(160, 260, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("background-color: rgb(143, 255, 147);")
        self.close_button.setObjectName("close_button")
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(20, 90, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_label.setFont(font)
        self.text_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        InfoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InfoWindow)
        self.close_button.clicked.connect(InfoWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InfoWindow)

    def retranslateUi(self, InfoWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoWindow.setWindowTitle(_translate("InfoWindow", "Info"))
        self.header_label.setText(_translate("InfoWindow", "Header"))
        self.close_button.setText(_translate("InfoWindow", "Закрыть"))
        self.text_label.setText(_translate("InfoWindow", "Text text text"))
