# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RulesWindow(object):
    def setupUi(self, RulesWindow):
        RulesWindow.setObjectName("RulesWindow")
        RulesWindow.resize(645, 517)
        RulesWindow.setStyleSheet("background-color: rgb(255, 230, 160);")
        self.centralwidget = QtWidgets.QWidget(RulesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header_label = QtWidgets.QLabel(self.centralwidget)
        self.header_label.setGeometry(QtCore.QRect(14, 28, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(280, 430, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("background-color: rgb(255, 200, 75);")
        self.close_button.setObjectName("close_button")
        self.epigraf_label = QtWidgets.QLabel(self.centralwidget)
        self.epigraf_label.setGeometry(QtCore.QRect(350, 100, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.epigraf_label.setFont(font)
        self.epigraf_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.epigraf_label.setWordWrap(True)
        self.epigraf_label.setIndent(5)
        self.epigraf_label.setObjectName("epigraf_label")
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(20, 210, 601, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_label.setFont(font)
        self.text_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        RulesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RulesWindow)
        self.close_button.clicked.connect(RulesWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RulesWindow)

    def retranslateUi(self, RulesWindow):
        _translate = QtCore.QCoreApplication.translate
        RulesWindow.setWindowTitle(_translate("RulesWindow", "Help"))
        self.header_label.setText(_translate("RulesWindow", "Header"))
        self.close_button.setText(_translate("RulesWindow", "Закрыть"))
        self.epigraf_label.setText(_translate("RulesWindow", "Epigraf"))
        self.text_label.setText(_translate("RulesWindow", "Text text text"))
