# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userlist_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserlistWindow(object):
    def setupUi(self, UserlistWindow):
        UserlistWindow.setObjectName("UserlistWindow")
        UserlistWindow.resize(664, 517)
        UserlistWindow.setStyleSheet("background-color: rgb(255, 230, 230);")
        self.centralwidget = QtWidgets.QWidget(UserlistWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stat_header = QtWidgets.QLabel(self.centralwidget)
        self.stat_header.setGeometry(QtCore.QRect(20, 10, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stat_header.setFont(font)
        self.stat_header.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_header.setObjectName("stat_header")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(290, 470, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("background-color: rgb(255, 180, 180);")
        self.close_button.setObjectName("close_button")
        self.stat_table = QtWidgets.QTableWidget(self.centralwidget)
        self.stat_table.setGeometry(QtCore.QRect(15, 61, 631, 391))
        self.stat_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.stat_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stat_table.setRowCount(1)
        self.stat_table.setColumnCount(6)
        self.stat_table.setObjectName("stat_table")
        self.stat_table.horizontalHeader().setCascadingSectionResizes(True)
        self.stat_table.horizontalHeader().setDefaultSectionSize(100)
        self.stat_table.horizontalHeader().setSortIndicatorShown(False)
        self.stat_table.horizontalHeader().setStretchLastSection(False)
        self.stat_table.verticalHeader().setVisible(False)
        UserlistWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserlistWindow)
        self.close_button.clicked.connect(UserlistWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserlistWindow)

    def retranslateUi(self, UserlistWindow):
        _translate = QtCore.QCoreApplication.translate
        UserlistWindow.setWindowTitle(_translate("UserlistWindow", "Statistics"))
        self.stat_header.setText(_translate("UserlistWindow", "Список игроков"))
        self.close_button.setText(_translate("UserlistWindow", "Закрыть"))
